test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    #exclude = ["change_url"]

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    #test_upgrade_from.COMMITCODE.name = "2.4.9"

